Update and rename blank.yml to Test-Entrega.yml

diff --git a/.github/workflows/Test-Entrega.yml b/.github/workflows/Test-Entrega.yml
--- a/.github/workflows/Test-Entrega.yml
+++ b/.github/workflows/Test-Entrega.yml
@@ -11,23 +11,23 @@ jobs:
       - name: Validar solo archivos PDF y pdsprj
         run: |
           # ls -1 lista todos los archivos
-          # | grep -vE '\.(jpeg|png|jpg|pdsprj)$' filtra y muestra los que no tienen las extensiones correctas
+          # | grep -vE '\.(jpeg|png|jpg|txt)$' filtra y muestra los que no tienen las extensiones correctas
           # && significa que si el comando anterior encuentra una coincidencia, ejecuta lo que sigue
-          ls -1 | grep -vE '\.(pdsprj|jpeg|jpg|png)$' && (echo "ERROR: ESE TIPO DE ARCHIVO NO HAY QUE SUBIR" && exit 1)
+          ls -1 | grep -vE '\.(txt|jpeg|jpg|png)$' && (echo "ERROR: ESE TIPO DE ARCHIVO NO HAY QUE SUBIR" && exit 1)
 
       - name: Creo variables por cada tipo de archivo a subir y la cantidad de archivos a subir
         run: |
-          echo "ArchivoPdsprj=8" >> $GITHUB_ENV
+          echo "ArchivoTxt=8" >> $GITHUB_ENV
           echo "ArchivoImagen=8" >> $GITHUB_ENV
 
-      - name: Verifica si se sube 1 archivo Pdsprj
+      - name: Verifica si se sube 1 archivo Txt
         run: |
-          test $(ls -1 *.pdsprj | wc -l) -eq ${{ env.ArchivoPdsprj }} || (echo "ERROR: NUMERO DE ARCHIVOS .pdsprj SUBIDOS INCORRECTO" && exit 1)
-          # -eq ${{ env.ArchivoPdsprj }} ahora usa la variable de entorno
+          test $(ls -1 *.txt | wc -l) -eq ${{ env.ArchivoTxt }} || (echo "ERROR: NUMERO DE ARCHIVOS .pdsprj SUBIDOS INCORRECTO" && exit 1)
+          # -eq ${{ env.ArchivoTxt }} ahora usa la variable de entorno
 
-      - name: Verificar tu nombre en los archivos PROTEUS
+      - name: Verificar tu nombre en los archivos Txt
         run: |
-          ls -1 *.pdsprj | grep ${{ github.actor }} || (echo "ERROR: UN ARCHIVO PDSPRJ NO TIENE TU NOMBRE" && exit 1)
+          ls -1 *.txt | grep ${{ github.actor }} || (echo "ERROR: UN ARCHIVO TXT NO TIENE TU NOMBRE" && exit 1)
 
       - name: Verifica si se sube 8 archivo jpeg|jpg|png
         run: |
@@ -37,10 +37,4 @@ jobs:
       - name: Verificar tu nombre en los archivos jpeg|jpg|png
         run: |
           ls -1 *.(jpeg|jpg|png) | grep ${{ github.actor }} || (echo "ERROR: UN ARCHIVO PDSPRJ NO TIENE TU NOMBRE" && exit 1)
-
-
-          
-
-      - name: Verificar tu nombre en los archivos PROTEUS
-        run: |
           ls -1 *.pdsprj | grep ${{ github.actor }} || (echo "ERROR: UN ARCHIVO PDSPRJ NO TIENE TU NOMBRE" && exit 1)
